import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
// import "./setting.css";
export default function ABC() {
  return (
    <>
      <Head>
        <title>page id</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="button-settings">page [id]</div>
    </>
  );
}
